// create arrays for each category
const pcGames = [
  'fallout NewVegas',
  'witcher',
  'resident Evil 7',
  'divinity original Sin',
  'Nier',
  'Horizon Zero Dawn',
  'Walking Dead: Michonne',
  'Dying Light',
  'Fire Watch',
  'Theif Gold',
  'Kingdom Come: Deliverance',
  'Half Life',
  'BioShock',
  'Hitman (buy 3rd game)',
  'Tomb Raider series',
  'Dark Souls',
  'Shadow Of War/Mordor',
  'Deus Ex',
  'Devil May Cry',
  'beyond good and evil',
  'minecraft',
  'GTA',
  'AssCreed Orgins',
  'Watch Dogs 2',
  'Alien Isolation',
  'Monkey Island',
  'Mass Effect',
  'The Outer Worlds',
  'Dishonored',
  'Nioh',
  'Vanquish',
  'subnautica',
  'phantom doctrine',
  'Diablo II',
  'dragon age',
  'BATMAN',
  'Elite dangerous',
  'Red Dead 2',
];

const ps4Games = [
  'God of war',
  'last of us 2',
  'spider man',
  'bloodborne',
  'ghost of tsusima',
  'death stranding',
  'persona 5',
  'ffXII',
  
  'Shadow of the Colossus',
  'Ratchet and clank',
  'the Last Gaurdian',
  'Kingdom Hearts'
];

const swtichGames = [
  'Bayonetta 2',
  'Shinigami IV',
  'Skyward Sword',
  'fire Emblem',
  'Mario Odyssey/galaxy',
  'No More Heros',
  'stardew valley',
  'Ori',
];

const classicGames = [
  'Zelda series',
  'parasite eve',
  'Xenosaga',
  'Asuras Wrath',
  'metriod Prime',
  'chrono trigger',
  'resident evil series',
  'dino crysis',
  'mario 64',
  'Onimusha',
  'Megaman legends',
  'Silent Hill',
  'Metal Gear',
  'Sonic Adventure',
  'Shenmue',
  'Max Payne',
  'Prince of Persia',
  'ico',
  'okami',
  'Dark Cloud',
  'Final Fantasy'
];

